hpi-studyu/studyu

app/lib/screens/study/report/sections/linear_regression_section_widget.dart, app/lib/screens/study/tasks/intervention/checkmark_task_widget.dart, app/lib/screens/study/tasks/observation/questionnaire_task_widget.dart, app/lib/widgets/fhir_questionnaire/annotated_scale_question_widget.dart, app/lib/widgets/fhir_questionnaire/boolean_question_widget.dart, app/lib/widgets/fhir_questionnaire/choice_question_widget.dart, app/lib/widgets/fhir_questionnaire/question_container.dart, app/lib/widgets/fhir_questionnaire/question_header.dart, app/lib/widgets/fhir_questionnaire/question_widget.dart, app/lib/widgets/fhir_questionnaire/questionnaire_widget.dart, app/lib/widgets/fhir_questionnaire/visual_analogue_question_widget.dart, app/pubspec.lock, app/pubspec.yaml, core/lib/models/questionnaire/question.dart, core/lib/models/questionnaire/questions/slider_question.dart, core/lib/models/report/report_specification.dart, core/lib/models/results/result.dart, core/lib/models/study/parse_study.dart, core/lib/models/study/parse_user_study.dart, core/lib/models/study/study.dart, core/lib/models/study/user_study.dart, core/pubspec.lock, core/pubspec.yaml, study_designer/analysis_options.yaml, study_designer/lib/dashboard.dart, study_designer/pubspec.lock, study_designer/pubspec.yaml
This questionnaire uses the FHIR Questionnaire model to store questions.
This will help in having a interoperable data model.
This also upgrades all packages to their null-safety versions.
=> Adds FHIR questionnaire compatibility

.github/workflows/publish_pubdev.yml
https://github.com/marketplace/actions/dart-and-flutter-package-publisher
=> chore: github workflow for publishing to pub.dev

core/lib/src/models/questionnaire/question_conditional.dart, core/lib/src/models/questionnaire/questions/annotated_scale_question.g.dart, core/lib/src/models/questionnaire/questions/boolean_question.g.dart, core/lib/src/models/questionnaire/questions/choice_question.g.dart, core/lib/src/models/questionnaire/questions/visual_analogue_question.g.dart, core/lib/src/models/report/sections/average_section.g.dart, core/lib/src/models/report/sections/linear_regression_section.g.dart, core/lib/src/models/results/result.dart, core/lib/src/models/study_results/results/numeric_result.g.dart, core/lib/src/models/study_schedule/study_schedule.g.dart, core/lib/src/models/tables/repo.g.dart, core/lib/src/models/tables/study.g.dart, core/lib/src/models/tables/subject_progress.g.dart, flutter_common/lib/envs/.env.staging, flutter_common/pubspec.yaml
This fixes the missing constructor errors, when generating the JSON IO code.
Fix: Adding new constructors in 9a25e1678f4c4e4ecb0859e763df41934db4df63
TODO before merging:
=> fix(core): Regenerating *.g.dart files for json_sequelize

core/lib/src/models/questionnaire/answer.dart
Fixes a bug that crashes the app when deserializing a List of Strings which are parsed incorrectly as dynamic objects.
=> fix: JSON Parse Error in Study Result

.github/workflows/build-docker-generator.yml
Adding keyless auth: https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
=> chore: Replace google cloud authentication scheme

designer_v2/lib/features/app.dart, designer_v2/lib/repositories/study_repository.dart, designer_v2/lib/services/notification_dispatcher.dart, designer_v2/lib/services/notification_service.dart, designer_v2/lib/services/notification_types.dart, designer_v2/lib/services/notifications.dart
=> Feat: Confirmation modal for destructive actions

database/migrate-v1_v2.sql, database/studyu-schema.sql
This reverts commit 1c92748b521af1601e91c497d85b72ab8f4672cf.
=> chore: revert "chore: remove redundant parenthesis"

.firebaserc, .github/workflows/firebase-hosting-merge-dev.yml, .github/workflows/firebase-hosting-pull-request.yml, firebase.json
dev App: [studyu-dev-app-2.web.app](https://studyu-dev-app-2.web.app)
dev Designer v2: [studyu-dev-designer-2.web.app](https://studyu-dev-designer-2.web.app)
=> chore(ci): Deploy dev branch builds to dev firebase project

app/ios/Podfile, app/ios/Podfile.lock, app/ios/Runner.xcodeproj/project.pbxproj, app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, app/ios/Runner/Info.plist, app/lib/l10n/app_de.arb, app/lib/l10n/app_en.arb, app/lib/screens/study/dashboard/contact_tab/contact_screen.dart, core/lib/src/models/contact.dart, core/lib/src/models/contact.g.dart, core/lib/src/util/analytics.g.dart, designer_v2/lib/features/design/info/study_info_form_controller.dart, designer_v2/lib/features/design/info/study_info_form_data.dart, designer_v2/lib/features/design/info/study_info_form_view.dart, designer_v2/lib/localization/app_de.arb, designer_v2/lib/localization/app_en.arb
=> Additional meta information

app/lib/screens/app_onboarding/about.dart, app/lib/screens/app_onboarding/terms.dart, app/lib/screens/app_onboarding/welcome.dart, app/lib/screens/study/dashboard/dashboard.dart, app/lib/screens/study/dashboard/settings.dart, app/lib/screens/study/dashboard/task_overview_tab/progress_row.dart, app/lib/screens/study/onboarding/consent.dart, app/lib/screens/study/onboarding/eligibility_screen.dart, app/lib/screens/study/onboarding/intervention_selection.dart, app/lib/screens/study/onboarding/journey_overview.dart, app/lib/screens/study/onboarding/kickoff.dart, app/lib/screens/study/onboarding/study_overview.dart, app/lib/screens/study/onboarding/study_selection.dart, app/lib/screens/study/report/sections/average_section_widget.dart, app/pubspec.lock, app/pubspec.yaml, core/pubspec.lock, core/pubspec.yaml, designer_v2/lib/common_views/icon_picker.dart, designer_v2/lib/features/auth/auth_form_controller.dart, designer_v2/lib/features/design/shared/questionnaire/question/question_form_controller.dart, designer_v2/lib/features/forms/form_validation.dart, designer_v2/lib/features/forms/form_view_model.dart, designer_v2/lib/features/recruit/invite_code_form_controller.dart, designer_v2/lib/utils/validation.dart, designer_v2/pubspec.lock, designer_v2/pubspec.yaml, flutter_common/pubspec.lock, flutter_common/pubspec.yaml
fixed breaking packages: material_design_icons_flutter, go_router, reactive_color_picker, reactive_forms
=> chore: upgrade deps

.github/labeler.yml, .github/workflows/pr.yml
=> Automatically assign PRs & add labels

CHANGELOG.md, app/CHANGELOG.md, app/pubspec.lock, app/pubspec.yaml, core/CHANGELOG.md, core/pubspec.yaml, designer_v2/CHANGELOG.md, designer_v2/pubspec.lock, designer_v2/pubspec.yaml, flutter_common/CHANGELOG.md, flutter_common/pubspec.lock, flutter_common/pubspec.yaml
- studyu_app@2.4.5
- studyu_core@4.3.0-dev.5
- studyu_designer_v2@1.3.7
- studyu_flutter_common@1.6.2-dev.6
=> Release: 26-06-2023

.dockerignore, docker/.gitignore, docker/README.md, docker/supabase/docker-compose-db.yml, docker/supabase/docker-compose.yml
=> feat(docker): Make Supabase use persistent volumes

CHANGELOG.md, app/CHANGELOG.md, app/pubspec.lock, app/pubspec.yaml, core/CHANGELOG.md, core/pubspec.yaml, designer_v2/CHANGELOG.md, designer_v2/pubspec.lock, designer_v2/pubspec.yaml, flutter_common/CHANGELOG.md, flutter_common/pubspec.lock, flutter_common/pubspec.yaml
- studyu_app@2.4.7
- studyu_core@4.3.0-dev.7
- studyu_designer_v2@1.3.9
- studyu_flutter_common@1.6.2-dev.8
=> chore(release): publish packages

app/android/app/src/main/AndroidManifest.xml, app/lib/screens/study/dashboard/dashboard.dart, designer_v2/pubspec.yaml, docs/uml/app/lib/screens/study/uml.svg, docs/uml/app/lib/screens/uml.svg, docs/uml/app/lib/uml.svg, docs/uml/app/lib/util/uml.svg, docs/uml/designer_v2/lib/features/auth/uml.svg, docs/uml/designer_v2/lib/features/design/reports/uml.svg, docs/uml/designer_v2/lib/features/design/uml.svg, docs/uml/designer_v2/lib/utils/uml.svg, flutter_common/lib/envs/.env
Pulls the following hotfix changes from `main` into into `dev`:
- https://github.com/hpi-studyu/studyu/pull/531
- https://github.com/hpi-studyu/studyu/pull/536
=> Merge hotfix changes to dev

CHANGELOG.md, app/CHANGELOG.md, app/lib/util/study_subject_extension.dart, app/pubspec.lock, app/pubspec.yaml, designer_v2/CHANGELOG.md, designer_v2/pubspec.lock, designer_v2/pubspec.yaml, docs/uml/flutter_common/lib/src/uml.svg, docs/uml/flutter_common/lib/src/utils/uml.svg, docs/uml/flutter_common/lib/uml.svg, flutter_common/CHANGELOG.md, flutter_common/lib/src/utils/storage.dart, flutter_common/lib/src/utils/user.dart, flutter_common/pubspec.lock, flutter_common/pubspec.yaml
- flutter_secure_storage needs synchronization to make sure that there are no concurrent I/O operations taking place. Before this PR, no signup was possible (https://github.com/hpi-studyu/studyu/pull/612/commits/2642597141653aa724a1305456e43840d6fbebe5 and https://github.com/hpi-studyu/studyu/pull/612/commits/7e97812279b77fb9406fb288341c0fd9e349ad9c)
- Exclude upload of multimodal results for web platform (https://github.com/hpi-studyu/studyu/pull/612/commits/27ba5298a1b714e1cc7e21a6d88c286f91e2907a)
=> fix: Hotfix for app signup

app/lib/screens/study/dashboard/dashboard.dart, app/lib/screens/study/dashboard/task_overview_tab/task_overview.dart, app/lib/screens/study/report/report_history.dart
This fix address UI overflows in screens when the system font size is increased. It also resolves the overflow of the text in the report story screen.
=> fix: UI overflows

designer_v2/lib/repositories/api_client.dart, designer_v2/lib/repositories/study_repository.dart
Fixed the issue where intervention and measurement data is missing when study is being duplicated
=> fix: duplicate study missing intervention & measurement data

CONTRIBUTING.md, melos.yaml
[Trello card](https://trello.com/c/yE5sZyda)
=> chore: make fvm optional with melos

database/studyu-schema.sql, supabase/seed.sql
New experimental database schema for template trials. This will still require future work like adapting the database tests and adding a migration script. But let's adapt the Designer code first and check if that is working fine, correct any bugs which might still be in the script, and then build around this in order to prevent additional work.
=> feat: New Template Trials Database Schema

app/lib/screens/study/dashboard/dashboard.dart, core/lib/src/models/tables/study_subject.dart
- made debug screen more reliable against exceptions
- result history only shows entries from own study_subjects
=> fix: App Debug Screen & Result history

app/lib/l10n/app_de.arb, app/lib/l10n/app_en.arb, app/lib/screens/study/dashboard/settings.dart, app/lib/util/schedule_notifications.dart
- Refactor notification leave screen
- Schedule notifications for 7 days instead of 3 in the future
=> fix: Notification improvements

CHANGELOG.md, app/CHANGELOG.md, app/android/gradle.properties, app/lib/util/debug_screen.dart, app/lib/util/notifications.dart, app/lib/util/schedule_notifications.dart, app/pubspec.yaml
Fixes notifications for release version
=> fix: disable R8 full mode for flutter_local_notifications

app/lib/screens/study/report/performance/performance_section.dart, app/lib/screens/study/report/sections/average_section_widget.dart
- Add tooltip to phase to indicate the number of days it represents
- Remove minimum indicator from the performance section
- Set maximum Y-axis value to the highest available data value
- Increase reserved size for side titles to prevent number truncation
=> feat: report overview

designer_v2/lib/features/account/account_settings.dart, designer_v2/lib/features/design/interventions/intervention_task_form_view.dart, designer_v2/lib/features/design/shared/questionnaire/question/question_form_view.dart, designer_v2/lib/features/design/shared/questionnaire/question/types/choice_question_form_view.dart, designer_v2/lib/features/design/shared/schedule/schedule_controls_view.dart
- Fixes bug that input fields on side sheets were not editable when using Firefox using suggested workaround
- Replaces hyperlink with correct TextButton
Old
New
=> fix: UI fixes
